# Generated by Django 4.0.3 on 2024-03-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(editable=False, max_length=20, verbose_name='Password'),
        ),
    ]
