# Generated by Django 4.0.3 on 2024-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=20, unique=True, verbose_name='Username'),
        ),
    ]
